name: Build and Push Docker image to GHCR

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      # - name: Prepare
      #   id: prep
      #   run: echo "IMAGE_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')-image" >> $GITHUB_ENV

      - uses: docker/metadata-action@v5.5.1
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/${{ steps.metadata.output.branch.name }}

      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
