name: Build and Push Docker image to GHCR

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Extract branch name from tag
        id: extract_branch
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/tags/}" | sed -E 's/-v[0-9.]+//')
          echo "branch=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "::set-output name=branch::${BRANCH_NAME}"

      - uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.branch }}

      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
